AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda to obtain the folder information
Resources:
  S3Info:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.info
      Runtime: nodejs6.10
      CodeUri: .
      Description: Lambda to obtain the folder information
      MemorySize: 128
      Timeout: 10
      Role: 'arn:aws:iam::229617835305:role/APIExecutionRole'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /serverless/info
            Method: GET
      Environment:
        Variables:
          bucket: drc-images
          masters_prefix: masters
          watermarked_prefix: watermarked
