AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Function to start the watermarking process on s3
Resources:
  S3Start:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.start
      Runtime: nodejs6.10
      CodeUri: .
      Description: Function to start the watermarking process on s3
      MemorySize: 128
      Timeout: 120
      Role: 'arn:aws:iam::229617835305:role/APIExecutionRole'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /serverless/start
            Method: POST
      Environment:
        Variables:
          bucket: drc-images
          masters_prefix: masters
          sns_waterwarking_sns_arn: 'arn:aws:sns:eu-west-1:229617835305:image_watermarking'
          watermarked_prefix: watermarked
